### PR TITLE
Version-Support for Minecraft 1.21.5

### PR DESCRIPTION
**Pull request by BlvckBytes**
Greetings!

I've cloned the existing `v1_21_R3` module into `v1_21_R4` and then iteratively ironed out various compilation errors and reflectively accessed member name/signature mismatches. So far, everything's up and working on `1.21.5`, assuming one also merges https://github.com/MyPetORG/MyPet/pull/1710 into their branch - as to not be stuck on broken commands which send complex messages.

Next up, the `versionmatcher.csv` on this repo's separate branch would need to (manually, probably) be extended by

```
1.21.5,v1_21_R4
```

I'm looking forward to feedback and or further improvements on this first attempt - here's a development build [plugins.zip](https://github.com/user-attachments/files/20037540/plugins.zip), and everybody's invited to report issues back to me.

Best Regards,
BlvckBytes

### CODE REVIEW

**Comment by YuanYuanOwO** [comment]
thanks for amazing work :D

**Comment by BlvckBytes** [comment]
Today, a server running my experimental build reported the following exception:

```
[16:30:41 ERROR]: Could not pass event PlayerQuitEvent to MyPet v3.12
java.lang.IllegalStateException: Cannot encode empty ItemStack
        at net.minecraft.world.item.ItemStack.save(ItemStack.java:598) ~[paper-1.21.5.jar:1.21.5-46-a74400d]
        at MyPet-3.12.3 by Bytes.jar/de.Keyle.MyPet.compat.v1_21_R4.util.inventory.ItemStackNBTConverter.itemStackToVanillaCompound(ItemStackNBTConverter.java:57) ~[MyPet-3.12.3 by Bytes.jar:?]
        at MyPet-3.12.3 by Bytes.jar/de.Keyle.MyPet.compat.v1_21_R4.util.inventory.ItemStackNBTConverter.itemStackToCompound(ItemStackNBTConverter.java:53) ~[MyPet-3.12.3 by Bytes.jar:?]
        at MyPet-3.12.3 by Bytes.jar/de.Keyle.MyPet.compat.v1_21_R4.util.inventory.ItemStackNBTConverter.itemStackToCompound(ItemStackNBTConverter.java:49) ~[MyPet-3.12.3 by Bytes.jar:?]
        at MyPet-3.12.3 by Bytes.jar/de.Keyle.MyPet.compat.v1_21_R4.PlatformHelper.itemStackToCompund(PlatformHelper.java:282) ~[MyPet-3.12.3 by Bytes.jar:?]
        at MyPet-3.12.3 by Bytes.jar/de.Keyle.MyPet.entity.types.MyWitherSkeleton.writeExtendedInfo(MyWitherSkeleton.java:68) ~[MyPet-3.12.3 by Bytes.jar:?]
        at MyPet-3.12.3 by Bytes.jar/de.Keyle.MyPet.entity.MyPet.getInfo(MyPet.java:91) ~[MyPet-3.12.3 by Bytes.jar:?]
        at MyPet-3.12.3 by Bytes.jar/de.Keyle.MyPet.repository.types.SqLiteRepository.savePet(SqLiteRepository.java:308) ~[MyPet-3.12.3 by Bytes.jar:?]
        at MyPet-3.12.3 by Bytes.jar/de.Keyle.MyPet.api.repository.MyPetManager.deactivateMyPet(MyPetManager.java:101) ~[MyPet-3.12.3 by Bytes.jar:?]
        at MyPet-3.12.3 by Bytes.jar/de.Keyle.MyPet.listeners.PlayerListener.on(PlayerListener.java:303) ~[MyPet-3.12.3 by Bytes.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.5-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:71) ~[paper-api-1.21.5-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.5.jar:1.21.5-46-a74400d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.5.jar:1.21.5-46-a74400d]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.5-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:517) ~[paper-1.21.5.jar:1.21.5-46-a74400d]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:504) ~[paper-1.21.5.jar:1.21.5-46-a74400d]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2157) ~[paper-1.21.5.jar:1.21.5-46-a74400d]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2136) ~[paper-1.21.5.jar:1.21.5-46-a74400d]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2122) ~[paper-1.21.5.jar:1.21.5-46-a74400d]
        at net.minecraft.network.Connection.handleDisconnection(Connection.java:866) ~[paper-1.21.5.jar:1.21.5-46-a74400d]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:270) ~[paper-1.21.5.jar:1.21.5-46-a74400d]
        at net.minecraft.server.MinecraftServer.tickConnection(MinecraftServer.java:1760) ~[paper-1.21.5.jar:1.21.5-46-a74400d]
        at net.minecraft.server.dedicated.DedicatedServer.tickConnection(DedicatedServer.java:385) ~[paper-1.21.5.jar:1.21.5-46-a74400d]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1736) ~[paper-1.21.5.jar:1.21.5-46-a74400d]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1527) ~[paper-1.21.5.jar:1.21.5-46-a74400d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1249) ~[paper-1.21.5.jar:1.21.5-46-a74400d]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:308) ~[paper-1.21.5.jar:1.21.5-46-a74400d]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

Caused by an empty (`net.minecraft.world.item.ItemStack#isEmpty`) item, which refuses to save into a `Tag`. I will investigate possible solutions soon and likely report back with a fix-commit.

NOTE: The exact same situation will also occur on 1.21.4 and should be patched within that corresponding module just as well (judging by my first glance).

https://github.com/MyPetORG/MyPet/blob/a284d60611176edc0af64ae1470cd532422b1318/modules/v1_21_R3/src/main/java/de/Keyle/MyPet/compat/v1_21_R3/util/inventory/ItemStackNBTConverter.java#L56-L58

**Comment by LOOHP** [comment]
Perhaps `AIR` items NBTs can be handled manually to maintain backwards compatibility?

**Comment by BlvckBytes** [comment]
> Perhaps `AIR` items NBTs can be handled manually to maintain backwards compatibility? Since it is the only exception where it refuses to parse since 1.20.5's item component changes.

I did partially learn about the new component notation while working on hover-events using show-item - how interesting! As far as I understand after a quick research session, they simply now also, as a separate change, omit empty items either completely, or represent them as an empty object `{}`. Since some call-sites of the mentioned-above method do not expect null-values, I guess that the following would be a valid solution:

```java
    public static CompoundTag itemStackToVanillaCompound(ItemStack itemStack) {
        if (itemStack == ItemStack.EMPTY) {
            return new CompoundTag();
        }

        return (CompoundTag) itemStack.save(registryAccess);
    }
```

Do you happen to have more detailed insights, knowing if that is indeed a valid approach? If so, I'd add it to all versions including 1.20.5 in my next commit.

Also, thank you for your kind words, ❤️

**Comment by LOOHP** [comment]
I'm not sure if it'll affect backwards compatibility or not, but for my own plugins, I've manually saved `AIR` using how it used to be pre-1.20.5:
```java
{id: "minecraft:air", count: 1}
```

**Comment by BlvckBytes** [comment]
> ```java
> {id: "minecraft:air", count: 1}
> ```

Does the new parser acknowledge this "legacy"-representation as an `ItemStack#EMPTY`? If so, I'll happily side with your solution! :)

**Comment by LOOHP** [comment]
No, it doesn't. The parser will also need to have this special case. However, if a post-1.20.5 server encounters a pre-1.20.5 database, our parser special case would be able to handle it. (So it'll point to air when an NBT with id `air` comes along)

That's the idea anyway. I'm not sure whether this probably would actually occur in MyPets tho, as I'm not that familiar with the internals.

**Comment by LOOHP** [comment]
Would be nice if you could provide the artifact for the new build :)

**Comment by BlvckBytes** [comment]
Right, I'm sorry - I was in a bit of a rush yesterday, and am also not at home at the current moment. I downloaded the artifact from a discord-chat I've sent it in yesterday and zipped it on my phone, then updated the url on the main post above.
