### ISSUE TITLE
Does not work with Spigot-1.8

### ISSUE THREAD

**Issue by lstep** [MyPetORG/MyPet#397]
Tried version 1.2.0 and the dev 1.2.1, without success:

```
[01:34:15] [Server thread/ERROR]: Error occurred while enabling MyPet v1.2.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R4/Packet
        at de.Keyle.MyPet.util.Configuration.setDefault(Configuration.java:175) ~[?:?]
        at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:138) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-"f15f0fc"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:333) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-"f15f0fc"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-"f15f0fc"]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:352) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-"f15f0fc"]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-"f15f0fc"]
```
